### ISSUE TITLE
Bug: Showing controls in website for navigation and fixing WASD controls.

### ISSUE THREAD

**Issue by bhimeshagrawal** [Glowstick0017/Little-Plane-Project#1]
It might help users figuring out how to navigate if they can see controls on website itself. I myself couldn't navigate without reading the readme file but I found the website way more interesting than reading the readme file.

**Comment by bhimeshagrawal** [comment]
You can assign me this issue if you think this feature would be relevant and useful, I will be happy to contribute.

**Comment by Glowstick0017** [comment]
sure, that was something originally planned, a context menu with instructions and commands would be a nice addition.

**Comment by bhimeshagrawal** [comment]
I just found out that WASD controls doesn't work if caps lock is ON, I'll fixing that too.
