### ISSUE TITLE
Refactor : using let instead var

### ISSUE THREAD

**Issue by isoletslicer** [Glowstick0017/Little-Plane-Project#2]
**Is your feature request related to a problem? Please describe.**
Given I saw your code using some `var`, not using let/const to be appropriate es6

**Describe the solution you'd like**
changing `var` to `let`

**Additional context**
I try to re run the webapp locally , it still running the command (e.g. teleport, seed) on my local with changing `var` to `let`

**Comment by isoletslicer** [comment]
You can assign me this issue if you think this feature would be relevant and useful, I will be happy to contribute.

or I could help you refactoring some codes if you may allow me to do it

**Comment by Glowstick0017** [comment]
feel free to make a pull request with the changes, I will gladly review and merge
