### ISSUE TITLE
Diagonal Movement

### ISSUE THREAD

**Issue by Richardhartleydev** [Glowstick0017/Little-Plane-Project#24]
Diagonal movement is faster than using the WASD keys for cardinal directions (up, down, left, right) .

If you move one unit to the right and one unit up in a single frame, the plane covers a greater distance diagonally compared to moving one unit solely along the X or Y axis, so maybe we can amend.

Pretty common issue in top-down games with lots of documentation to fix online. (Good first issue fix)

**Comment by Glowstick0017** [comment]
I've experimented with different ways to solve this issue, like cutting the movement speed in half while diagonal movement is being done, issues arise with either the generation or with the coordinates displayed, it also feels somewhat more natural for some reason when the plane moves diagonally in whole intervals. I'm open to PRs changing this.

**Comment by Glowstick0017** [comment]
Closing due to PR https://github.com/Glowstick0017/Little-Plane-Project/pull/40
