### ISSUE TITLE
Add a dash to the plane's movepool

### ISSUE THREAD

**Issue by MellowMancer** [Glowstick0017/Little-Plane-Project#32]
I noticed that the plane's movement is a little slow and takes a considerable amount to time to cover a screen's length of distance. But I understand why the base speed is set that low.

So I believe a dash would be a neat addition to the plane's moveset to allow users to dash momentarily if they wish to backtrack faster or just wish to explore a little faster.

**Comment by Glowstick0017** [comment]
originally I made it so if the shift key was pressed down, movement would be doubled, since speed can be changed by the user anyways and theres no challenge to get to places fast, that would work for now, but in the future a dash with visual cooldown would be nice.
