### ISSUE TITLE
Enhance performance of perlin draw

### ISSUE THREAD

**Issue by christianfds** [Glowstick0017/Little-Plane-Project#33]
**Is your feature request related to a problem? Please describe.**
At lower quality the rendering gets way slower

**Describe the solution you'd like**
Draw to an offscreen already greatly improves the rendering

**Describe alternatives you've considered**
Batching drawing might also help, didn't test it yet.

**Additional context**
Already implemented the off screen drawing playing in the console and got a huge improvement in performance.

**Comment by christianfds** [comment]
If you want I can finish the testing with batching

**Comment by Glowstick0017** [comment]
how does this affect the drawing when starting the application or high movement speed

**Comment by christianfds** [comment]
Since the rendering is striclity linked with the movement instead of a target fps/tps, higher rendering speed will make the movement feel faster and smother. It does not affect the startup of the application
