### ISSUE TITLE
Implementation of a angle-based direction system

### ISSUE THREAD

**Issue by theDRB123** [Glowstick0017/Little-Plane-Project#37]
**Is your feature request related to a problem? Please describe.**
I was wondering if we could put some kind  rotation system for changing the direction of the airplane like it would rotate cw / ccw when respective keys are pressed 

**Describe the solution you'd like**
We might be able to add a fPlayerA type variable which has the current angle of the Airplane , and the direction-change speed depends on the playerAngle ... 

**Additional context**

Here are a few screenshots where i have implemented this in c++ { this is the basic game-engine project of javidx9) 

![image](https://github.com/Glowstick0017/Little-Plane-Project/assets/119250923/3276a6d7-b44b-4e95-a8e2-faa4bf999583)
![image](https://github.com/Glowstick0017/Little-Plane-Project/assets/119250923/9bb932b2-e0a8-4add-800a-21afce182946)

i would like to get this feature allotted to me . Thank you.

**Comment by theDRB123** [comment]
hello , i am very new to contributing , i am sorry if this is wrong place to ask , is there any discord server i may join to discuss or ask doubts ...

**Comment by Glowstick0017** [comment]
@theDRB123 there's not currently a server for TLPP but there is one for [hacktoberfest](https://discord.gg/hacktoberfest) and my [personal discord server](https://discord.gg/pdZAaUMQEe) which can be used to ask some questions in
