### ISSUE TITLE
color command broken

### ISSUE THREAD

**Issue by Glowstick0017** [Glowstick0017/Little-Plane-Project#38]
This change is amazing especially with increasing the quality, however after merging, i did some more testing and realized the color command no longer displays the underlying perlin plane.

https://github.com/Glowstick0017/Little-Plane-Project/issues/36#issuecomment-1751868847_

**Comment by christianfds** [comment]
Hey @Glowstick0017 sorry about that, forgot to test this out, my bad!
If you wish I can quickly fix it, or we can leave this to someone else that is also engaging with hacktoberfest. I will leave this decision up to you.

**Comment by Glowstick0017** [comment]
@christianfds if it's not too much, a quick fix would be good, there's plenty of other issues open for new contributors.

**Comment by christianfds** [comment]
Sure! Just give me a few seconds to fix it and I will send a PR
