### ISSUE TITLE
Bug: pixel color change on movement.

### ISSUE THREAD

**Issue by Glowstick0017** [Glowstick0017/Little-Plane-Project#41]
PR https://github.com/Glowstick0017/Little-Plane-Project/pull/40 introduced angle based rotation which looks amazing, however in doing so the exact coordinates are now by single increments rather than by 10s (the default quality value). This means when moving slightly diagonally, the perlin plane redraws with slightly different values for each block. 

The beginning of a fix for this is found around https://github.com/Glowstick0017/Little-Plane-Project/blob/3acc86fbb5acba561c12a82fa2f0d80d5fcb45c9/engine/Engine.js#L115-L124
If we change the return to something like 
```javascript
return (
    (perlin2((x + (Math.round(posX/quality)*quality)) / heightFromGround, (y + (Math.round(posY/quality)*quality)) / heightFromGround) +
      mountainHeight) /
    2
  );
```
This will make it so that at every quality, each color block on the map will stay the same color upon any movement. The problem with this fix is, it will make movement itself clunkier.

**Comment by anttijankeri** [comment]
I made a PR for a fix for this issue.

**Comment by Glowstick0017** [comment]
@anttijankeri thank you for the fix, I'm going to leave this issue open for a little longer because although the change fixed the problem it introduces the offset block near the edges of the pane. I'd like to see if anyone wants to try tackling that offset or if anyone would like to find a different way to get around the block change original problem.
