### ISSUE TITLE
Use number key

### ISSUE THREAD

**Issue by damodar04** [Glowstick0017/Little-Plane-Project#49]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. why we always use S,Z,X Key why we didn't use any number key .

**Describe the solution you'd like**
So if we added the number key function so its easy to operate beacause tere is less number od numerical keys instant of word keys

**Comment by Glowstick0017** [comment]
@damodar04 I'm sorry, I don't really understand. Can you describe what the number keys will be replacing or the function you're looking at.
