### ISSUE TITLE
Dashing bug in the not-constantly-moving mode

### ISSUE THREAD

**Issue by Rikir-M** [Glowstick0017/Little-Plane-Project#62]
**Description of the bug**
In the not-constantly-moving mode, when I press dash key, the dash doesn't work. It only works when I press one of the direction keys.

**To Reproduce**
1. Enable the not-constantly-moving mode by pressing 'e' key
2. Press dash key (space bar)
3. Press any direction key (w, a, d, up, left, right)

**Expected behavior**
Dashing works properly by pressing dash key (space bar).

**Desktop:**
 - OS: Windows
 - Browser: Chrome

**Comment by Rikir-M** [comment]
Also, I've noticed that when holding the space key in constantly-moving mode, dashing seems laggy. I'd like to suggest the feature that holding space key works the same as pressing space key. No dashing again, just dashing once.

**Comment by Glowstick0017** [comment]
To be honest, I'll be fine with doing away with dashing as a whole; it doesn't seem a very realistic feature for flying. Not that we're necessarily going for realistic but since you can already change your speed with a command, I don't see the use for dashing.

**Comment by Rikir-M** [comment]
Ah I get it. So, no dashing function? I think I can work on removing the whole dashing function.

**Comment by Glowstick0017** [comment]
I'm fine with just the removal of the dashing function, I'll assign this issue to you. That being said, I know I just talked about realism, but maybe we can replace dashing with maybe a 'sprint' kind of feature where holding down the shift key increases movement speed.

**Comment by Rikir-M** [comment]
Ahh that's a good idea! I'll try to implement that. Thanks for assigning this to me.

**Comment by Glowstick0017** [comment]
dashing has now been removed and replaced with movement speed changes with up/down directions

**Comment by Rikir-M** [comment]
oh got it. Thanks for notifying!

> dashing has now been removed and replaced with movement speed changes with up/down directions
