### ISSUE TITLE
Enhance Documentation, Contribution Guidelines, and Code Structure

### ISSUE THREAD

**Issue by techSaswata** [Glowstick0017/Little-Plane-Project#64]
1. Improve Documentation
Title: Improve Documentation for Setup and Usage Instructions
Description: The README currently lacks detailed instructions on setting up and running the project. Adding sections for project setup, dependencies, and usage examples would help new users get started more easily. Including a "Features" section and a brief project overview would also enhance clarity.

2. Add Contribution Guidelines
Title: Add Contribution Guidelines
Description: The project lacks a CONTRIBUTING.md file with clear guidelines for contributing. Adding instructions on coding standards, submitting issues, and creating pull requests would make it easier for new contributors to participate.

3. Improve Code Structure and Comments
Title: Improve Code Structure and Comments
Description: Certain parts of the code are not well-documented and lack sufficient comments to explain complex logic. Adding comments and restructuring the code for better readability would enhance maintainability and ease of understanding.

**Comment by Glowstick0017** [comment]
please see #21
