### ISSUE TITLE
Proposed Refactoring of Controls.js for Improved Readability and Performance

### ISSUE THREAD

**Issue by vlazic** [Glowstick0017/Little-Plane-Project#7]
Hello!

I've been looking into your plane project and it's clear to see the effort put into creating an engine from scratch, especially with the focus on perlin noise and procedural generation.

While reviewing the `Controls.js` file, I've identified a few areas where we can enhance code readability and performance. I'm outlining these observations and proposed changes below and would appreciate feedback before initiating a pull request.

### Observations:
1. **Hardcoded Keys:** The current setup uses hardcoded key values. This approach might make future changes or extensions to the control keys a bit tedious.
2. **Lack of Modularity:** The movement functionalities (up, down, left, right) are intertwined within the game loop. This structure can make the code harder to follow.
3. **Redundant Code:** The `keydown` and `keyup` event listeners have redundant sections which we could optimize for brevity.
4. **Performance Concerns:** The canvas undergoes a redraw during every iteration of the game loop. This behavior might lead to unnecessary performance overheads.

### Proposed Changes:
1. **Use Constants for Keys:** By transitioning to named constants for keys, we can make the code more understandable and facilitate future modifications.
2. **Modularize Movement:** By segregating movement-related functionalities into distinct functions (`moveUp`, `moveDown`, `moveLeft`, `moveRight`), we can enhance code readability.
3. **Optimize Event Listeners:** Streamlining the `keydown` and `keyup` event listeners will not only reduce redundancy but also make the codebase cleaner.
4. **Performance Improvement:** Introducing a `needsRedraw` flag can help ensure the canvas redraws only when necessary, potentially offering a significant boost in performance.

### Conclusion
By implementing these changes, I believe we can make `Controls.js` more maintainable and efficient. I'd appreciate feedback on this proposal and, upon agreement, would be eager to start working on a pull request.

Thank you for considering these suggestions.

**Comment by Glowstick0017** [comment]
A big part of this project to me was making it so that whoever reads the code can easily understand what’s going on and learn from it. Any changes to make the readability of this code better would be greatly appreciated. I’d happy review and merge changes if everything is still in working order.
